a = [
"Travis Saly",
"LaPorsha Robinson",
"Christina gambler",
"nyra almond",
"Ashley Stewart",
"Cornelius cole",
"Neil Bibbs",
"Carmen Rosario Castro",
"Pee Da Don",
"Sylvens (Dark Wolf) Bellanton",
"Fred Birks",
"Camilo Henao",
"Latesha Everhart",
"Perry Jeter",
"Michael Sanchez",
"Martha charry",
"Joel Jones",
"Rodney Doss",
"Que Royal",
"Calvin Linton",
"Roxanne Henderson Washington",
"Tahnee Mims",
"Tonisha peebles",
"Chris Wilkinson",
"Mary Jane Wilkerson",
"Reginald Jenkins",
"Ray Romilla",
"Tamashia Jones",
"Tejuan Browder",
"Neil Turner",
"Derek S. O'Neal Sr.",
"Shaneequa Graham",
"Qazi Mahmood",
"Andre D Mayfield",
"Gregg Fluellen",
"Candace Myrickes",
"Aaron Howard",
"maurice h thomas",
"Rico Darrow Adams",
"Tracy Michelle Story",
]
b = [i.split(' ')[0] for i in a]