# Generated by Django 3.1.4 on 2021-01-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing_portal', '0006_auto_20210121_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Monthly'), (3, 'Yearly')], null=True),
        ),
    ]
