# Generated by Django 3.1.4 on 2021-01-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financing_portal', '0008_auto_20210121_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchasedmodel',
            name='product',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='financing_portal.product'),
            preserve_default=False,
        ),
    ]
