STRIPE_CONFIG = {
    "STRIPE_PUBLISHABLE_KEY_TEST": 'pk_test_k8aDNdIlHgXwyIJIf1tswxny00h0Xyel4S',
    "STRIPE_SECRET_KEY_TEST": 'sk_test_ZZa6QOdZS7mz9Xo17MxQHRgM00ozbxBI5g',

    "STRIPE_PUBLISHABLE_KEY_PROD": 'pk_live_WdBBxb5xLQfPv4DCkjFiZLyh008ifSciL4',
    "STRIPE_SECRET_KEY_PROD": 'sk_live_lQ8z3GZD05P6mW2MHEU7cf8o00Kph0qFvZ'
}
