# Generated by Django 3.0.5 on 2020-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
