# Generated by Django 3.0.5 on 2020-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanportal', '0006_auto_20200423_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='uploads/documents/90016a37-d42f-4b9c-90a7-637f88ab7784/'),
        ),
    ]
