# Generated by Django 3.0.5 on 2020-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanportal', '0007_auto_20200423_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='documents/11cff469-84b7-4d69-b0f8-a97f9bf03214/'),
        ),
    ]
