# Generated by Django 3.0.5 on 2020-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanportal', '0008_auto_20200423_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='documents/3a120790-853c-11ea-88eb-f2189835783a/'),
        ),
    ]
