# Generated by Django 3.0.5 on 2020-04-23 08:30

from django.db import migrations, models
import loanportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('loanportal', '0009_auto_20200423_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=loanportal.models.get_file_path),
        ),
    ]
