# Generated by Django 3.2.5 on 2021-08-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('dynamic', '0075_subdomain_show_bcb_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='show_bcb_software',
        ),
    ]
