# Generated by Django 3.2.5 on 2021-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0087_alter_subdomain_navigation_bar_link_2_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='footer_text',
            field=models.TextField(default='We Help Businesses Acquire Business Credit With Our Free Software, Mobile App, & Google Chrome Extension. Also, We Have A Free Personal Credit, Marketing, & Business Credit Course In Our Software As Well.', max_length=500, verbose_name='Footer text'),
        ),
    ]
