# Generated by Django 3.0.5 on 2020-06-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20200626_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
