# Generated by Django 3.0.5 on 2020-06-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_usersteps_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersteps',
            old_name='domain_name_name',
            new_name='domain_name_act',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='fax_number_number',
            new_name='fax_number_act',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='professional_email_address_address',
            new_name='professional_email_address_act',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='toll_free_number_number',
            new_name='toll_free_number_act',
        ),
    ]
