# Generated by Django 3.0.5 on 2020-06-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20200626_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersteps',
            old_name='domain_name_act',
            new_name='website_act',
        ),
    ]
