# Generated by Django 3.0.5 on 2020-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20200626_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='domain_act',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual domain name'),
        ),
    ]
