# Generated by Django 3.0.3 on 2020-04-22 14:55

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountofresiduals', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=500, null=True)),
                ('payout_date', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelresiduals_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'residuals',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
