# Generated by Django 3.0.5 on 2020-05-07 12:04

from django.db import migrations, models
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomingapartner',
            name='logo',
            field=models.FileField(null=True, upload_to=whitelabelpartnerportal.models.get_file_path),
        ),
    ]
