# Generated by Django 3.0.5 on 2020-04-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('whitelabelpartnerportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalresiduals_profile', to='user.Profile'),
        ),
        migrations.AlterModelTable(
            name='residuals',
            table='whitelabelpartnerportal_residuals',
        ),
    ]
