# Generated by Django 3.0.5 on 2020-04-22 20:10

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('whitelabelpartnerportal', '0002_auto_20200422_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountofresiduals', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=500, null=True)),
                ('payout_date', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalresidual_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_residual',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Residuals',
        ),
    ]
