# Generated by Django 3.0.5 on 2020-04-22 20:42

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('whitelabelpartnerportal', '0006_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='applied',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='created',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, null=True)),
                ('client_email', models.CharField(max_length=50)),
                ('client_phone_number', models.CharField(max_length=50)),
                ('updates_made', models.CharField(max_length=500, null=True)),
                ('residual_amount', models.CharField(max_length=500, null=True)),
                ('expected_payout', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalfreeprogram_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_free_program',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
