# Generated by Django 3.0.5 on 2020-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0008_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateresidual',
            name='payout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceduedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='payout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='residual',
            name='payout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payout_date',
            field=models.DateTimeField(null=True),
        ),
    ]
