# Generated by Django 3.0.5 on 2020-04-22 21:11

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('whitelabelpartnerportal', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeprogram',
            name='client_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freeprogram',
            name='client_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceamount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceduedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_placed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BankPaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_number', models.CharField(max_length=500, null=True)),
                ('name_of_bank', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=500, null=True)),
                ('name_on_bank_account', models.CharField(max_length=500, null=True)),
                ('your_address', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalbankpaymentinformation_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_bank_payment_information',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
