# Generated by Django 3.0.5 on 2020-04-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0011_auto_20200422_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='amountofresiduals',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='payout_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='product',
        ),
        migrations.AddField(
            model_name='lead',
            name='Business_package',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
