# Generated by Django 3.0.5 on 2020-04-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0012_auto_20200422_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Business_package',
            new_name='business_package',
        ),
    ]
