# Generated by Django 3.0.5 on 2020-04-22 21:51

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('whitelabelpartnerportal', '0015_paypalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelabelWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=500, null=True)),
                ('website_link', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwhitelabelwebsite_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_whitelabel_website',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WhitelabelPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_portal', models.CharField(default='', max_length=500, null=True)),
                ('paid_portal', models.CharField(default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwhitelabelportal_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_whitelabel_portal',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WhitelabelBusinessPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_login', models.CharField(max_length=500, null=True)),
                ('toll_free_number_login', models.CharField(max_length=500, null=True)),
                ('professional_email_address_login', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwhitelabelbusinesspackage_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_whitelabel_business_package',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwebinar_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_webinars',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50, null=True)),
                ('account_name', models.CharField(max_length=500, null=True)),
                ('amount_paid', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalpayment_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_payments',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
