# Generated by Django 3.0.5 on 2020-04-23 12:45

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('whitelabelpartnerportal', '0016_payment_webinar_whitelabelbusinesspackage_whitelabelportal_whitelabelwebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, null=True)),
                ('client_email', models.CharField(max_length=50, null=True)),
                ('client_phone_number', models.CharField(max_length=50, null=True)),
                ('updates_made', models.CharField(max_length=500, null=True)),
                ('residual_amount', models.CharField(max_length=500, null=True)),
                ('expected_payout', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalpaidprogram_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_paid_program',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
